########################################################
############### Creating a Progress Bar ################
########################################################

import time, os              # import time and OS libraries/modules (in order to 'play' with system time)

print("--------------------------------------------------   0% COMPLETE")
time.sleep(1.5)
os.system("clear")
print("#####---------------------------------------------  10% COMPLETE")
time.sleep(2)
os.system("clear")
print("##########----------------------------------------  19% COMPLETE")
time.sleep(1.5)
os.system("clear")
print("###############-----------------------------------  27% COMPLETE")
time.sleep(1)
os.system("clear")
print("####################------------------------------  42% COMPLETE")
time.sleep(2)
os.system("clear")
print("#########################-------------------------  50% COMPLETE")
time.sleep(1.5)
os.system("clear")
print("##################################----------------  65% COMPLETE")
time.sleep(2)
os.system("clear")
print("#######################################-----------  73% COMPLETE")
time.sleep(2.5)
os.system("clear")
print("############################################------  81% COMPLETE")
time.sleep(3)
os.system("clear")
print("#################################################-  99% COMPLETE")
time.sleep(5)
os.system("clear")
print("################################################## 100% COMPLETE")
time.sleep(5)
os.system("clear")

print("Your Download is now ready! Enjoy!  :) ")
time.sleep(2)
print("Please note: Downloading peer-to-peer Music is (still) illegal! :( ")
